language: android
sudo: required
android: 
  components: 
    - build-tools-23.0.1
    - android-23
    - extra-android-m2repository
before_cache:
	- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
before_install:
	- sudo apt-get update
install:
	- sudo apt-get install -y build-essential
	- sudo apt-get install -y cmake git libgtk2.0-dev pkg-config libavcodec-dev libavformat-dev libswscale-dev
	- sudo apt-get install -y python-dev python-numpy libtbb2 libtbb-dev libjpeg-dev libpng-dev libtiff-dev libjasper-dev libdc1394-22-dev
before_script:
	- git clone https://github.com/Itseez/opencv.git --branch 3.1.0
	#- git clone https://github.com/Itseez/opencv_contrib.git --branch 3.1.0
	- cd opencv
	- mkdir build
	- cd build
	- cmake -D CMAKE_BUILD_TYPE=RELEASE ..
	- make -j8
	- sudo make -j8 install
	- cd ../..
	#-D OPENCV_EXTRA_MODULES_PATH=~/opencv_contrib/modules
	# Install Android NDK 
	# Note: There is now a difference between Target architecture and Platform architecture. What SHOULD they be?
	- REVISION="10e"
	- ARCH=$(uname -m)
	- FILE="android-ndk-r${REVISION}-linux-${ARCH}.bin"
	- wget http://dl.google.com/android/ndk/${FILE}
	- chmod a+x ${FILE}
	- ./${FILE} > /dev/null
	- export ANDROID_NDK_HOME=$PWD/android-ndk-r${REVISION}
script: TERM=dumb gradle assemble test
