name: Build APK

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the 'main' branch
  pull_request:
    branches:
      - main  # Trigger the workflow for pull requests to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Checkout your repository

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # Set up OpenJDK 11

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake libgtk2.0-dev pkg-config libavcodec-dev libavformat-dev libswscale-dev libtbb2 libtbb-dev libjpeg-dev libpng-dev libtiff-dev libjasper-dev libdc1394-22-dev

      - name: Set up Android SDK
        run: |
          echo "Installing Android SDK"
          mkdir -p $HOME/Android/Sdk
          wget https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip
          unzip commandlinetools-linux-7583922_latest.zip -d $HOME/Android/Sdk
          yes | $HOME/Android/Sdk/cmdline-tools/bin/sdkmanager --sdk_root=$HOME/Android/Sdk --update
          yes | $HOME/Android/Sdk/cmdline-tools/bin/sdkmanager --sdk_root=$HOME/Android/Sdk "platform-tools" "build-tools;30.0.3" "platforms;android-30"

      - name: Set up Android NDK
        run: |
          NDK_VERSION="21.4.7075529"
          wget https://dl.google.com/android/repository/android-ndk-${NDK_VERSION}-linux-x86_64.zip
          unzip android-ndk-${NDK_VERSION}-linux-x86_64.zip -d $HOME/Android/ndk
          export ANDROID_NDK_HOME=$HOME/Android/ndk/android-ndk-${NDK_VERSION}

      - name: Build APK
        run: |
          ./gradlew assembleRelease  # Or use 'assembleDebug' depending on the desired build type

      - name: Upload APK as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: app-release-apk
          path: app/build/outputs/apk/release/*.apk  # Adjust path based on your project structure
